/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MethodRouteImport } from './routes/method'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as ApiIndexIdRouteImport } from './routes/api.$indexId'
import { Route as IIndexIdRouteImport } from './routes/i.$indexId'
import { Route as StatsIndexIdRouteImport } from './routes/stats.$indexId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexIdRoute = ApiIndexIdRouteImport.update({
  id: '/api/$indexId',
  path: '/api/$indexId',
  getParentRoute: () => rootRouteImport,
} as any)
const IIndexIdRoute = IIndexIdRouteImport.update({
  id: '/i/$indexId',
  path: '/i/$indexId',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexIdRoute = StatsIndexIdRouteImport.update({
  id: '/stats/$indexId',
  path: '/stats/$indexId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/statistics': typeof StatisticsRoute
  '/api/$indexId': typeof ApiIndexIdRoute
  '/i/$indexId': typeof IIndexIdRoute
  '/stats/$indexId': typeof StatsIndexIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/statistics': typeof StatisticsRoute
  '/api/$indexId': typeof ApiIndexIdRoute
  '/i/$indexId': typeof IIndexIdRoute
  '/stats/$indexId': typeof StatsIndexIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/statistics': typeof StatisticsRoute
  '/api/$indexId': typeof ApiIndexIdRoute
  '/i/$indexId': typeof IIndexIdRoute
  '/stats/$indexId': typeof StatsIndexIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/method'
    | '/statistics'
    | '/api/$indexId'
    | '/i/$indexId'
    | '/stats/$indexId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/method'
    | '/statistics'
    | '/api/$indexId'
    | '/i/$indexId'
    | '/stats/$indexId'
  id:
    | '__root__'
    | '/'
    | '/method'
    | '/statistics'
    | '/api/$indexId'
    | '/i/$indexId'
    | '/stats/$indexId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodRoute: typeof MethodRoute
  StatisticsRoute: typeof StatisticsRoute
  ApiIndexIdRoute: typeof ApiIndexIdRoute
  IIndexIdRoute: typeof IIndexIdRoute
  StatsIndexIdRoute: typeof StatsIndexIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$indexId': {
      id: '/api/$indexId'
      path: '/api/$indexId'
      fullPath: '/api/$indexId'
      preLoaderRoute: typeof ApiIndexIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$indexId': {
      id: '/i/$indexId'
      path: '/i/$indexId'
      fullPath: '/i/$indexId'
      preLoaderRoute: typeof IIndexIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/$indexId': {
      id: '/stats/$indexId'
      path: '/stats/$indexId'
      fullPath: '/stats/$indexId'
      preLoaderRoute: typeof StatsIndexIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodRoute: MethodRoute,
  StatisticsRoute: StatisticsRoute,
  ApiIndexIdRoute: ApiIndexIdRoute,
  IIndexIdRoute: IIndexIdRoute,
  StatsIndexIdRoute: StatsIndexIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
